2.20. Разметка внутренней страницы
htmlacademy-htmlcss/1655025-technomart-31 pull request #3
Opened 2021-05-25 22:04 UTC by RomaVB23

2021-05-25 22:37 UTC, RomaVB23 commented on catalog.html
> +                        <a href="#">ФИЛЬТР:</a>
Фильтр и Сортировка без ссылок
отправил и понял, что не исправил

Так то это  p
от них никуда же не переходим

и где нажать, чтоб больше выбрать кода?
а то при первом же + на строчке пишится комментарий
а хотелось выбрать больше строчек кода


вопрос тупой
согласен)
но вот что-то не пойму

2021-05-26 22:12 UTC, Zakamsky commented on catalog.html
> +                        <a href="#">ФИЛЬТР:</a>
Что бы выделить несколько строк - надо нажать и потянуть за плюсик

2021-05-26 22:16 UTC, Zakamsky commented on catalog.html
> +                        <a href="#">ФИЛЬТР:</a>
ок про Р кажется понял.

2021-05-26 23:02 UTC, Zakamsky requested changes
Хорошо поработал над ошибками страницы, но что то поторопился в каталоге, футер мимо кассы положил, и еще ряд ошибок в разметке, но кажется что в основном от спешки и невнимательности, будь аккуратнее пожалуйста.
Спасибо за комментарии в коде и вопросы.
Давай поправим все перед новой темой. 
И проверь себя в валидаторе пожалуйста, все грубые ошибки он бы тебе подсказал.
ай, и добавь в меню пожалуйста ссылку на вторую страницу с главной =)

2021-05-27 16:06 UTC, RomaVB23 commented
мда....
это конечно и есть спешка
но всё равно - это не оправдание мне, такую туфту по факту прислал
извиняюсь, больше такого не повториться 
и прежде чем отправить проверю в валидаторе 
сейчас исправлю

2021-05-27 22:33 UTC, Zakamsky reviewed
Отличная работа над ошибками. Не надо извинений, все ошибаются, но мало кто признает.
Я вот тоже получается ошибся. Теперь у нас отличный html каркаса на который можно добавить стили.

2021-05-27 22:33 UTC, Zakamsky commented on catalog.html
> +                     -->
Спасибо за вопрос, давай мыслить чуть шире макета, нам не надо реализовывать ссылку "куда то", немного абстракции - если зайти в любой интернет магазин, в карточке товара есть ссылка по которой можно прочитать о товаре подробнее выбрать цвет, кол-во, понять чем отличается bfg 6000 от  bfg 3000...
У нас ее нет в макете, но это не значит что мы можем игнорировать этот факт, в дальнейшем нам ее тоже закажут и еще денег заплатят. А пока мы ее вставляем как ссылку в меню, на какую то категорию - с заглушкой в адресе - href="#"

2021-05-27 22:33 UTC, Zakamsky commented on catalog.html
> +                        <a href="#">25500 Р.</a>
Блин, вот я тоже поспешил и у меня в тексте комментария `<br>` превратился в перенос, поэтому стало непонятно о чем я писал... стыд мне и позор =)
в общем тут перенос на новую строку ссылки лучше оформить из стилей, а `<br>` для переноса текста использовать а не для разрывов между элементами.

2021-05-27 22:34 UTC, merged